In [2]:
import numpy as np
a1 = np.array([3,2,5,6])
a1

array([3, 2, 5, 6])

In [4]:
print( a1.ndim)
a = np.ones ((3,4))
print (a)


1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
a3 = np.arange(1,6)
a3

array([1, 2, 3, 4, 5])

In [7]:
aA= np.array([2,3,4])
aB= np.array([4,5,6])
print(aA+aB)

[ 6  8 10]


In [8]:
b = np.array([[1,3,5], [23,3,4], [3,4,5]])
print(b.ndim)

2


In [9]:
c = np.linspace(1,5,10)
print(c)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [10]:
d = np.array([[6,7,8], [1,2,3], [9,3,2]])
print(d[0:2,2])

[8 3]


In [11]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
b = a>3
print(a[b])

[4 5]
